/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filesharingappmain;

import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Henkok
 */
public class Home extends javax.swing.JFrame {
    public ConnectionManager connMan;
    public String sendPath;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //this.jProgressBar1.setUI(new ProgressCircularBar());
        connMan = new ConnectionManager(this, Thread.currentThread());
//        jProgressBar1.setValue(75);
//        jProgressBar1.setUI(new ProgressCircularBar());
//        jProgressBar1.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
//        jProgressBar1.setStringPainted(true);
//        jProgressBar1.setFont(jProgressBar1.getFont().deriveFont(24f));
//        jProgressBar1.setForeground(Color.cyan);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        sharingPanelsWrapper = new javax.swing.JPanel();
        sharingHome = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        destinationFolder = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        sharingProgress = new javax.swing.JPanel();
        sendingPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        sharingActionDescriber = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        connectingStatus = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        sharingPanelsWrapper.setBackground(new java.awt.Color(102, 255, 0));
        sharingPanelsWrapper.setLayout(new java.awt.CardLayout());

        jButton3.setText("Create");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Join");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("destination folder - ");

        destinationFolder.setText("D fjasdfasdgsdgsadg:\\Henok Dejen\\Academic");

        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setText("change");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sharingHomeLayout = new javax.swing.GroupLayout(sharingHome);
        sharingHome.setLayout(sharingHomeLayout);
        sharingHomeLayout.setHorizontalGroup(
            sharingHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sharingHomeLayout.createSequentialGroup()
                .addGroup(sharingHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sharingHomeLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sharingHomeLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        sharingHomeLayout.setVerticalGroup(
            sharingHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sharingHomeLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(sharingHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(sharingHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sharingHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(destinationFolder))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        sharingPanelsWrapper.add(sharingHome, "card3");

        sendingPath.setText("jTextField1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Send");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        sharingActionDescriber.setText("Waiting for sharing....");

        javax.swing.GroupLayout sharingProgressLayout = new javax.swing.GroupLayout(sharingProgress);
        sharingProgress.setLayout(sharingProgressLayout);
        sharingProgressLayout.setHorizontalGroup(
            sharingProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sharingProgressLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sharingProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sharingProgressLayout.createSequentialGroup()
                        .addComponent(sharingActionDescriber)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sharingProgressLayout.createSequentialGroup()
                        .addComponent(sendingPath, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(sharingProgressLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sharingProgressLayout.setVerticalGroup(
            sharingProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sharingProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sharingProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendingPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(27, 27, 27)
                .addComponent(sharingActionDescriber)
                .addGap(56, 56, 56)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        sharingPanelsWrapper.add(sharingProgress, "card2");

        connectingStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connectingStatus.setText("Connectoin Failed!");
        connectingStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("X");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setDoubleBuffered(true);
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sharingPanelsWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(connectingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sharingPanelsWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectingStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pickFileToSend();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.showConnectingStatus("waiting others to connect ...");
        new Thread(new MainRunnable(connMan, true)).start();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:       
        String url = JOptionPane.showInputDialog(rootPane, "enter server ip address");
        if (url.length() > 0) {
            this.connMan.url = url;
            try {
                new Thread(new MainRunnable(connMan, false)).start();
            }

            catch(Exception e) {
                e.printStackTrace();
                this.showNoConnection();
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Invalid IP");
            url = JOptionPane.showInputDialog(rootPane, "enter server ip address");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Thread(new Runnable() {
            @Override
            public void run() {
                try{
                    connMan.setUpSending(sendPath);
                }
                catch(Exception e){
                }
            }
        }).start(); 
        //this.updateProgressBar(this.jProgressBar1.getValue() + 10);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            this.connMan.DESTINATION_FOLDER = file.getPath();
            this.destinationFolder.setText(file.getPath());
        }        //fileChooser
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.connMan.socket = null;  
        showNoConnection();
    }//GEN-LAST:event_jButton6ActionPerformed

    
    public void pickFileToSend() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            sendPath = file.toString();            
            sendingPath.setText(file.toString());
        }        
    }
    
    public void showSharingProgressPanel() {
        this.sharingPanelsWrapper.removeAll();
        this.sharingPanelsWrapper.repaint();
        this.sharingPanelsWrapper.revalidate();
        
        this.sharingPanelsWrapper.add(this.sharingProgress);
        this.sharingPanelsWrapper.repaint();
        this.sharingPanelsWrapper.revalidate();        
    }
    
    public void showSharingHome() {
        this.sharingPanelsWrapper.removeAll();
        this.sharingPanelsWrapper.repaint();
        this.sharingPanelsWrapper.revalidate();
        
        this.sharingPanelsWrapper.add(this.sharingHome);
        this.sharingPanelsWrapper.repaint();
        this.sharingPanelsWrapper.revalidate();    
    }
    
    public void showConnectedStatus() {
        this.jPanel3.setBackground(Color.GREEN);
        this.connectingStatus.setText("Connected!");
    }
    
    public void showConnectingStatus(String message) {
        this.jPanel3.setBackground(Color.YELLOW);
        this.connectingStatus.setText(message);    
    }
    
    public void showNoConnection() {
        this.jPanel3.setBackground(Color.RED);
        this.connectingStatus.setText("Connection Failed!");    
    }
    
    
    public void setSharingAction(String message) {
        this.sharingActionDescriber.setText(message);
    }
    
    public void updateProgressBar(int width) {
        this.jProgressBar1.setValue(width);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectingStatus;
    private javax.swing.JLabel destinationFolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField sendingPath;
    private javax.swing.JLabel sharingActionDescriber;
    private javax.swing.JPanel sharingHome;
    private javax.swing.JPanel sharingPanelsWrapper;
    private javax.swing.JPanel sharingProgress;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanelsWrapper() {
        return sharingHome;
    }
}
